apiVersion: apps/v1
kind: Deployment
metadata:
  name: govind
  labels:
    app: govind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: govind
  template:
    metadata:
      labels:
        app: govind
    spec:
      containers:
      - name: govind
        image: uk.icr.io/govindarajan/app
        ports:
        - containerPort: 8080
